services:
  web:
    image: php:8.1-apache
    volumes:
      - ./www:/var/www/html  # Монтируем директорию сайта в контейнер
      - ./apache-config.conf:/etc/apache2/sites-enabled/000-default.conf  # Добавляем конфиг Apache
    ports:
      - "8081:80"  # Открываем порт 80 для веб-сервера
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    command: >
      bash -c "apt-get update && apt-get install -y apache2-utils ssl-cert &&
               a2enmod proxy proxy_http ssl &&
               apache2-foreground"
