services:
  web:
    image: php:8.1-apache
    volumes:
      - ./www:/var/www/html  # Монтируем директорию сайта в контейнер
    ports:
      - "8081:80"  # Открываем порт 80 для веб-сервера
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
